services:
  client-backend:
    container_name: spring-application
    image: backend:0.1.1
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://service-db:5432/profitsoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - jobify-network
  frontend:
    container_name: react-application
    image: frontend:0.1.1
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - jobify-network
  service-db:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profitsoft
    ports:
      - "5432:5432"
    networks:
      - jobify-network
networks:
    jobify-network:
        driver: bridge