### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "recruiter",
  "password": "recruiter",
  "first_name": "Recruiter",
  "last_name": "Bondar"
}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "hellow",
  "password": "hellow"
}

###
PUT http://localhost:8080/api/v1/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIkFQUExZX1ZBQ0FOQ1kiLCJWSUVXX1ZBQ0FOQ1kiLCJVUERBVEVfT1dOX1BST0ZJTEUiLCJHRVRfT1dOX1BST0ZJTEUiXSwiaWQiOjIsImVtYWlsIjoidXNlcjEyIiwic3ViIjoidXNlcjEyIiwiaWF0IjoxNzMyNDgzODk3LCJleHAiOjE3MzI0ODk4OTd9.PmMghfQeBcdEgUdtf1MJxrda10n4QMu0QM-WMi2mKd8

{
  "first_name": "Vladyslav",
  "last_name": "Koval"
}

###
PUT http://localhost:8080/api/v1/developers/update-to-admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJwZXJtaXNzaW9ucyI6WyJWSUVXX1ZBQ0FOQ1kiLCJVUERBVEVfT1dOX1BST0ZJTEUiLCJBUFBMWV9WQUNBTkNZIiwiR0VUX09XTl9QUk9GSUxFIiwiVklFV19PV05fQVBQTElDQVRJT05TIl0sImlkIjo0LCJ1c2VybmFtZSI6ImhlbGxvdyIsInN1YiI6ImhlbGxvdyIsImlhdCI6MTczMzI2MjE1MywiZXhwIjoxNzMzMjY4MTUzfQ.AJDuavbqVlfDHaikuijGBJDlosgvfG1gbv7wTi2JJaU

###
GET http://localhost:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer