name: CI Jobify

on:
  pull_request:
    branches: [ master ]

jobs:
  storage-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Docker
        uses: docker/setup-buildx-action@v3
      - name: Change directory
        run: cd ./storage-service
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Run tests
        run: npm run test